os: linux
dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
  - master

on:
  tags: true

before_deploy:
- git config --local user.name "cmorganl"
- git config --local user.email "c.morganlang@gmail.com"

env:
  global:
  - CIBW_SKIP="cp27-* pp27-* *-manylinux_i686"
  - TWINE_USERNAME=__token__
  # Note: TWINE_PASSWORD is set to an API token in Travis settings
  - PIP="python3 -m pip"
  - TWINE_REPOSITORY=pypi
  - TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
  - TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}

jobs:
  include:
  - services: docker
  - os: osx
    language: shell

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      git -C "$(brew --repo)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git;
    fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      sudo apt -y install gcc dpkg-dev curl zip git libz-dev python3-distutils python3-dev;
    fi

install:
  - "$PIP install -r requirements.txt"
  - "$PIP install -U setuptools"
  - "$PIP install cibuildwheel==1.1.0"
  - "$PIP install --upgrade pip"
  - "$PIP --version"
  - "$PIP install codecov"
  - "$PIP install twine"
  - "$PIP install tox-travis"

script:
  # tox -a: List the environments available, nothing else
  # tox -v: Run the selected environments. This is controlled by tox-travis on Travis CI, and the [travis] env in tox.ini
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      tox -a;
      tox -v;
    fi
  - python3 -m cibuildwheel --output-dir wheelhouse
  - python3 setup.py sdist --dist-dir wheelhouse

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
- ls wheelhouse/
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    $PIP install twine;
    python3 -m twine upload --skip-existing wheelhouse/*.whl;
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      python3 -m twine upload --skip-existing wheelhouse/*.whl wheelhouse/*tar.gz;
  fi